export const REQUEST_USERS_SITE 		= 'REQUEST_USERS_SITE';
export const RECEIVE_USERS_SITE_SUCCESS = 'RECEIVE_USERS_SITE_SUCCESS';
export const RECEIVE_USERS_SITE_FAIL 	= 'RECEIVE_USERS_SITE_FAIL';


export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';


export const CREATE_NEW_LOCAL_PAGE_ELEMENT 				= 'CREATE_NEW_LOCAL_PAGE_ELEMENT';
export const CREATE_NEW_LOCAL_PAGE_ELEMENTS_FOR_GROUP 	= 'CREATE_NEW_LOCAL_PAGE_ELEMENTS_FOR_GROUP';
export const UPDATE_LOCAL_PAGE_ELEMENT_GROUP 			= 'UPDATE_LOCAL_PAGE_ELEMENT_GROUP';


export const REQUEST_CREATE_GROUP 	= 'REQUEST_CREATE_GROUP';
export const CREATE_GROUP_SUCCESS 	= 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAIL 		= 'CREATE_GROUP_FAIL';


export const REQUEST_DELETE_GROUP 	= 'REQUEST_DELETE_GROUP';
export const DELETE_GROUP_SUCCESS 	= 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAIL 		= 'DELETE_GROUP_FAIL';



export const REQUEST_UPDATE_PAGE 	= 'REQUEST_UPDATE_PAGE';
export const UPDATE_PAGE_SUCCESS 	= 'UPDATE_PAGE_SUCCESS';
export const UPDATE_PAGE_FAIL 		= 'UPDATE_PAGE_FAIL';


export const REQUEST_NEW_PAGE 			= 'REQUEST_NEW_PAGE';
export const CREATE_NEW_PAGE_SUCCESS 	= 'CREATE_NEW_PAGE_SUCCESS';
export const CREATE_NEW_PAGE_FAIL 		= 'CREATE_NEW_PAGE_FAIL';
export const REQUEST_DELETE_PAGE 		= 'REQUEST_DELETE_PAGE';
export const DELETE_PAGE_SUCCESS 		= 'DELETE_PAGE_SUCCESS';
export const DELETE_PAGE_FAIL 			= 'DELETE_PAGE_FAIL';


export const REQUEST_DELETE_PAGE_ELEMENTS 	= 'REQUEST_DELETE_PAGE_ELEMENTS';
export const DELETE_PAGE_ELEMENTS_SUCCESS 	= 'DELETE_PAGE_ELEMENTS_SUCCESS';
export const DELETE_PAGE_ELEMENTS_FAIL 		= 'DELETE_PAGE_ELEMENTS_FAIL';


export const RECEIVE_FORM_ELEMENTS 	= 'RECEIVE_FORM_ELEMENTS';
export const LOAD 					= 'LOAD';
export const ON_FIELD_CHANGE 		= 'ON_FIELD_CHANGE';


export const REQUEST_IMAGE_UPLOAD 	= 'REQUEST_IMAGE_UPLOAD';
export const IMAGE_UPLOAD_SUCCESS 	= 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAIL 		= 'IMAGE_UPLOAD_FAIL';
export const REQUEST_IMAGE_DELETE 	= 'REQUEST_IMAGE_DELETE';
export const DELETE_IMAGE_SUCCESS 	= 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAIL 		= 'DELETE_IMAGE_FAIL';

export const RESET_FORM_SUCCESS = 'RESET_FORM_SUCCESS';

export const DRAG_PAGE_ITEM = 'DRAG_PAGE_ITEM';
export const DRAG_PAGE_ELEMENT_GROUP_SLIDE = 'DRAG_PAGE_ELEMENT_GROUP_SLIDE';


export const REQUEST_UPDATE_PAGE_SORT_ORDER = 'REQUEST_UPDATE_PAGE_SORT_ORDER';
export const UPDATE_PAGE_SORT_ORDER_SUCCESS = 'UPDATE_PAGE_SORT_ORDER_SUCCESS';
export const UPDATE_PAGE_SORT_ORDER_FAIL 	= 'UPDATE_PAGE_SORT_ORDER_FAIL';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REQUEST_USER_SESSION = 'REQUEST_USER_SESSION';
export const USER_SESSION_SUCCESS = 'USER_SESSION_SUCCESS';
export const USER_SESSION_FAIL = 'USER_SESSION_FAIL';

export const REQUEST_PUBLISH_SITE = 'REQUEST_PUBLISH_SITE';
export const PUBLISH_SITE_SUCCESS = 'PUBLISH_SITE_SUCCESS';
export const PUBLISH_SITE_FAIL = 'PUBLISH_SITE_FAIL';
