export const REQUEST_USERS_SITE = 'REQUEST_USERS_SITE';
export const RECEIVE_USERS_SITE_SUCCESS = 'RECEIVE_USERS_SITE_SUCCESS';
export const RECEIVE_USERS_SITE_FAIL = 'RECEIVE_USERS_SITE_FAIL';

export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';

export const CREATE_NEW_LOCAL_PAGE_ELEMENT = 'CREATE_NEW_LOCAL_PAGE_ELEMENT';
export const CREATE_NEW_LOCAL_PAGE_ELEMENTS_FOR_GROUP = 'CREATE_NEW_LOCAL_PAGE_ELEMENTS_FOR_GROUP';
// export const CREATE_NEW_LOCAL_PAGE_ELEMENT_GROUP = 'CREATE_NEW_LOCAL_PAGE_ELEMENT_GROUP';
export const UPDATE_LOCAL_PAGE_ELEMENT_GROUP = 'UPDATE_LOCAL_PAGE_ELEMENT_GROUP';
// export const REQUEST_DELETE_PAGE_ELEMENTS_SLIDE = 'REQUEST_DELETE_PAGE_ELEMENTS_SLIDE';
// export const DELETE_PAGE_ELEMENTS_SLIDE_SUCCESS = 'DELETE_PAGE_ELEMENTS_SLIDE_SUCCESS';
// export const DELETE_PAGE_ELEMENTS_SLIDE_FAIL = 'DELETE_PAGE_ELEMENTS_SLIDE_FAIL';



export const REQUEST_CREATE_GROUP = 'REQUEST_CREATE_GROUP';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL';


export const REQUEST_UPDATE_PAGE = 'REQUEST_UPDATE_PAGE';
export const UPDATE_PAGE_SUCCESS = 'UPDATE_PAGE_SUCCESS';
export const UPDATE_PAGE_FAIL = 'UPDATE_PAGE_FAIL';

export const REQUEST_NEW_PAGE = 'REQUEST_NEW_PAGE';
export const CREATE_NEW_PAGE_SUCCESS = 'CREATE_NEW_PAGE_SUCCESS';
export const CREATE_NEW_PAGE_FAIL = 'CREATE_NEW_PAGE_FAIL';
export const REQUEST_DELETE_PAGE = 'REQUEST_DELETE_PAGE';
export const DELETE_PAGE_SUCCESS = 'DELETE_PAGE_SUCCESS';
export const DELETE_PAGE_FAIL = 'DELETE_PAGE_FAIL';

export const REQUEST_DELETE_PAGE_ELEMENTS = 'REQUEST_DELETE_PAGE_ELEMENTS';
export const DELETE_PAGE_ELEMENTS_SUCCESS = 'DELETE_PAGE_ELEMENTS_SUCCESS';
export const DELETE_PAGE_ELEMENTS_FAIL = 'DELETE_PAGE_ELEMENTS_FAIL';

export const RECEIVE_FORM_ELEMENTS = 'RECEIVE_FORM_ELEMENTS';
export const LOAD = 'LOAD';
export const ON_FIELD_CHANGE = 'ON_FIELD_CHANGE';

